# Generated by Django 5.2.6 on 2025-09-16 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, help_text='Место выполнения привычки', max_length=256, null=True, verbose_name='Место выполнения привычки')),
                ('time', models.TimeField(help_text='Введите время выполнения привычки', verbose_name='Время')),
                ('action', models.CharField(help_text='Действие, которое нужно выполнить', max_length=256, verbose_name='Действие, которое нужно выполнить')),
                ('is_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Периодичность выполнения в днях', verbose_name='Периодичность выполнения в днях')),
                ('execution_time', models.PositiveSmallIntegerField(default=120, help_text='Длительность выполнения в секундах', verbose_name='Длительность выполнения в секундах')),
                ('award', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, help_text='Данные признак указывается только для Полезной привычки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthy_habits_tracker.habit', verbose_name='Связанная приятная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
